stages:
- build
- clean
  
build:
  stage: build
  script:
  - ./gradlew clean
  - ./gradlew build 
  - du -h build/exe/ygo_win_counter/*/*
  when: on_success
  except:
  - tags

clean:
  stage: clean
  script:
  - ./gradlew clean
  when: always
  except:
  - tags
